### PR TITLE
Luki broke my code and doesn't want to admit it

### PR DESCRIPTION
**Pull request by RuntimeOverflow**

### CODE REVIEW

**Comment by JezWalmsley** [comment]
Fix it then, simple /s

**Comment by Luki120** [comment]
Smh a peasant has come here, anyways, imma just have fun changing the PR title again :hihi:

**Comment by JezWalmsley** [comment]
What did you just call me 😠

**Comment by RuntimeOverflow** [comment]
Luki do be rude, no wonder he got banned from Twickd.

**Comment by Luki120** [comment]
WHERE'S THE /S smh

**Pull request merged**
