### PR TITLE
add my name

### LINKED ISSUE #5: my name isnt in contributors
where is my name
where is my name

### PR DESCRIPTION
**Pull request by Exerra**
this tweak has my name
so
add me in the contributors page at the very top, ez

### CODE REVIEW

**Comment by Exerra** [comment]
I can just merge it myself but I'ma let @Luki120 have the honours

**Comment by Exerra** [comment]
20ish

**Review by Luki120 — CHANGES_REQUESTED** [review]
Hello there fellow user! Thank you for your contribution! However.. before merging:

Fix the indentation smh, tab delimited, just like it was before, pretty and clean, thank uu!

**Comment by Exerra** [comment]
> Hello there fellow user! Thank you for your contribution! However.. before merging:
> 
> Fix the indentation smh, tab delimited, just like it was before, pretty and clean, thank uu!

goddamnit ok check it now

**Pull request merged**
